### ISSUE TITLE
How To Use Open ID with ASP.NET

### ISSUE THREAD

**Issue by Engineerumair** [onelogin/openid-connect-dotnet-core-sample#1]
Hello,
There are two flows for openID authentication
Implicit flow and Authentication flow
The sample code is provide for the following technologies

Node + Express + Passport
Dotnet Core 2.0
Ruby on Rails
Java - Spring 

But I didn't find for just ASP.NET application, is openID can be integrated in ASP.NET application?

if not, can I use implicit flow and implement it through javascript in my ASP.NET application.

thanks for your cooperation.

**Comment by Engineerumair** [comment]
Is same code of ASP.NET MVC can be used in webform to integrate openID connect into my app so that I can add that app into onelogin.

**Comment by richet** [comment]
For older versions of ASP.NET you will need to use OWIN. This blog post might help you get started with that http://www.cloudidentity.com/blog/2014/07/24/protecting-an-asp-net-webforms-app-with-openid-connect-and-azure-ad/

Alternately, if you have a single page app backed by an ASP.NET API then the Implicit Flow could work for you. We have a [sample here that uses javascript only](https://github.com/onelogin/onelogin-oidc-node/tree/master/2.%20Implicit%20Flow).
