### ISSUE TITLE
Missing OneLogin OIDC Client ID Placeholders in readme.md

### ISSUE THREAD

**Issue by BrandonSchreck** [onelogin/openid-connect-dotnet-core-sample#3]
The read me file suggests there are placeholders that should be replaced but I don't see any.

> Replace the <OneLogin OIDC Client ID> etc placeholders with your own values from OneLogin.

**Comment by andrewrod33** [comment]
Looks like it's referring to https://github.com/onelogin/openid-connect-dotnet-core-sample/blob/f1c9f3aab07abc25627040136792ba5efe9a3f14/Startup.cs#L20 and https://github.com/onelogin/openid-connect-dotnet-core-sample/blob/f1c9f3aab07abc25627040136792ba5efe9a3f14/Startup.cs#L21
